# Generated by Django 3.0.7 on 2020-08-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_volunteering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
